
export const presetArticleTags = [
    "Literature", "Fiction", "Non-fiction", "Poetry", "Short Stories",
    "Novels", "Essays", "Biographies", "Memoirs", "Book Reviews",
    "Writing Tips", "Creative Writing", "Storytelling", "Character Development", "Plot Structure",
    "World-building", "Editing", "Publishing", "Self-publishing", "Literary Criticism",
    "Classic Literature", "Contemporary Literature", "Science Fiction", "Fantasy", "Mystery",
    "Thriller", "Romance", "Historical Fiction", "Young Adult", "Children's Literature",
    "Graphic Novels", "Comic Books", "Manga", "Fanfiction", "Literary Theory",
    "Narrative Techniques", "Writing Prompts", "Author Interviews", "Book Recommendations", "Reading Lists",
    "Bookstores", "Libraries", "E-books", "Audiobooks", "Literary Festivals",
    "Writing Workshops", "Book Clubs", "Literary Awards", "Bestsellers", "Indie Authors",
    "Reading Habits", "Speed Reading", "Critical Reading", "Close Reading", "Comparative Literature",
    "Book Collecting", "Rare Books", "First Editions", "Book Binding", "Book Conservation",
    "Literary Genres", "Literary Devices", "Symbolism", "Metaphors", "Allegory",
    "Foreshadowing", "Unreliable Narrator", "Stream of Consciousness", "Epistolary", "Magical Realism",
    "Gothic Literature", "Dystopian Fiction", "Utopian Fiction", "Speculative Fiction", "Alternate History",
    "Steampunk", "Cyberpunk", "Urban Fantasy", "Epic Fantasy", "High Fantasy",
    "Low Fantasy", "Sword and Sorcery", "Hard Science Fiction", "Soft Science Fiction", "Space Opera",
    "Time Travel", "Parallel Universes", "Post-Apocalyptic", "Supernatural", "Paranormal",
    "Horror", "Psychological Thriller", "Crime Fiction", "Noir", "Hardboiled",
    "Cozy Mystery", "Police Procedural", "Legal Thriller", "Espionage", "Historical Mystery",
    "Contemporary Romance", "Historical Romance", "Paranormal Romance", "Regency Romance", "Gothic Romance",
    "Chick Lit", "Women's Fiction", "Literary Fiction", "Experimental Fiction", "Postmodern Literature",
    "Modernist Literature", "Realism", "Naturalism", "Surrealism", "Absurdism",
    "Existentialism", "Transcendentalism", "Romanticism", "Victorian Literature", "Elizabethan Literature",
    "Renaissance Literature", "Medieval Literature", "Ancient Literature", "Epic Poetry", "Lyric Poetry",
    "Narrative Poetry", "Sonnets", "Haiku", "Free Verse", "Slam Poetry",
    "Prose Poetry", "Autobiography", "Memoir", "Travelogue", "Personal Essays",
    "Literary Journalism", "Nature Writing", "Food Writing", "Sports Writing", "Science Writing",
    "Tech Writing", "Medical Writing", "Legal Writing", "Academic Writing", "Business Writing",
    "Grant Writing", "Copywriting", "Content Writing", "Blogging", "Microblogging",
    "Flash Fiction", "Vignettes", "Novellas", "Serial Fiction", "Choose Your Own Adventure",
    "Interactive Fiction", "Hypertext Fiction", "Visual Novels", "Wordless Books", "Picture Books",
    "Chapter Books", "Middle Grade", "New Adult", "Adult Fiction", "Literary Classics",
    "Shakespeare", "Jane Austen", "Charles Dickens", "Mark Twain", "Virginia Woolf",
    "Ernest Hemingway", "F. Scott Fitzgerald", "George Orwell", "J.R.R. Tolkien", "Agatha Christie",
    "Stephen King", "J.K. Rowling", "Gabriel García Márquez", "Haruki Murakami", "Chimamanda Ngozi Adichie",
    "Banned Books", "Controversial Literature", "Censorship", "Freedom of Expression", "Intellectual Freedom",
    "Literary Movements", "Literary Periods", "Literary Traditions", "World Literature",
    "Translation Studies", "Linguistics", "Philology", "Etymology", "Semantics",
    "Syntax", "Grammar", "Punctuation", "Style Guides", "Proofreading",
    "Copy Editing", "Developmental Editing", "Line Editing", "Substantive Editing", "Fact-Checking",
    "Research Methods", "Primary Sources", "Secondary Sources", "Archival Research", "Oral History",
    "Digital Humanities", "Text Mining", "Corpus Linguistics", "Computational Linguistics", "Natural Language Processing",
    "Book Design", "Cover Design", "Typography", "Page Layout", "Illustration",
    "Book Marketing", "Author Platform", "Book Promotion", "Book Trailers", "Book Tours",
    "Literary Agents", "Publishing Houses", "Small Presses", "Vanity Publishing", "Hybrid Publishing",
    "Print-on-Demand", "Ebook Formatting", "ISBN", "Copyright", "Intellectual Property",
    "Public Domain", "Creative Commons", "Fair Use", "Plagiarism", "Attribution",
    "Ghostwriting", "Collaboration", "Co-authoring", "Writing Partnerships", "Writing Groups",
    "Writers' Retreats", "Writing Residencies", "MFA Programs", "Creative Writing Degrees", "Literary Internships",
    "Literacy", "Reading Comprehension", "Reading Strategies", "Active Reading", "Analytical Reading",
    "Reading Challenges", "Summer Reading", "Bedtime Stories", "Storytime", "Read-Alouds",
    "Silent Reading", "Skimming", "Scanning", "Note-taking",
    "Marginalia", "Bookmarking", "Highlighting", "Annotating", "Book Journaling",
    "Reading Logs", "Reading Reflections", "Book Reports",
    "Reader Response", "Distant Reading", "Comparative Reading", "Cross-referencing",
    "Intertextuality", "Allusions", "References", "Quotations", "Epigraphs",
    "Dedications", "Acknowledgments", "Forewords", "Prefaces", "Introductions",
    "Afterwords", "Epilogues", "Appendices", "Glossaries", "Indexes",
    "Bibliographies", "Works Cited", "Footnotes", "Endnotes", "Citations",
    "Book Formats", "Hardcover", "Paperback", "Mass Market Paperback", "Trade Paperback",
    "Leather-bound", "Limited Editions", "Signed Copies", "Advance Reader Copies", "Galley Proofs",
    "Manuscripts", "Typescripts", "Handwritten Drafts", "Revision Process", "Beta Readers",
    "Critique Partners", "Writing Critique", "Peer Review", "Workshop", "Writing Circles",
    "NaNoWriMo", "Script Frenzy", "Poetry Month", "Book Week", "Literacy Day",
    "Banned Books Week", "World Book Day", "Read Across America", "Free Comic Book Day", "Independent Bookstore Day",
    "Literary Tourism", "Authors' Homes", "Literary Landmarks", "Book Towns", "Literary Museums",
    "Library Science", "Archival Studies", "Information Science", "Cataloging", "Classification Systems",
    "Dewey Decimal System", "Library of Congress Classification", "Reference Services", "Circulation", "Interlibrary Loan",
    "Digital Libraries", "Open Access", "Institutional Repositories", "Digital Archives", "Preservation",
    "Rare Book Librarianship", "Special Collections", "Manuscript Collections", "Oral History Collections",
    "Literary Societies", "Book Fairs", "Literary Conferences", "Writers' Conferences", "Book Expos",
    "Book Signings", "Author Readings", "Literary Salons", "Poetry Slams", "Open Mic Nights",
    "Storytelling Events", "Literary Debates", "Book Discussions", "Reading Groups", "Literature Circles",
    "Book to Film Adaptations", "Book to TV Adaptations", "Book to Stage Adaptations", "Book to Game Adaptations", "Transmedia Storytelling",
    "Fan Fiction", "Fan Art", "Cosplay", "Role-Playing Games", "Literary-inspired Games",
    "Bookish Merchandise", "Literary Gifts", "Bookends", "Bookmarks", "Book Sleeves",
    "Reading Lights",
   
]